const config = require('tailwind-config/tailwind.config.js');
const defaultTheme = require('tailwindcss/defaultTheme');

// ensures all theme styles are generated by tailwind at build-time
const colorList = [
  'primary',
  'secondary',
  'gmc-dune',
  'gmc-jungle',
  'gmc-forest',
  'gmc-heart',
  'gmc-glacier',
  'gmc-beach',
  'gmc-surf',
  'gmc-soil',
  'gmc-berry',
  'gmc-sunset',
  'gmc-ocean',
];

const safeList = [];

for (const color of colorList) {
  safeList.push(`text-${color}`);
  safeList.push(`bg-${color}`);
  safeList.push(`text-${color}-dark-10`);
  safeList.push(`bg-${color}-dark-10`);
  safeList.push(`text-${color}-dark-20`);
  safeList.push(`bg-${color}-dark-20`);
  safeList.push(`text-${color}-dark-30`);
  safeList.push(`bg-${color}-dark-30`);
  safeList.push(`text-${color}-dark-40`);
  safeList.push(`bg-${color}-dark-40`);
  safeList.push(`text-${color}-dark-50`);
  safeList.push(`bg-${color}-dark-50`);
  safeList.push(`text-${color}-light-10`);
  safeList.push(`bg-${color}-light-10`);
  safeList.push(`text-${color}-light-20`);
  safeList.push(`bg-${color}-light-20`);
  safeList.push(`text-${color}-light-30`);
  safeList.push(`bg-${color}-light-30`);
  safeList.push(`text-${color}-light-40`);
  safeList.push(`bg-${color}-light-40`);
  safeList.push(`text-${color}-light-50`);
  safeList.push(`bg-${color}-light-50`);
}

config.safelist = safeList;
config.darkMode = 'class';
config.theme.borderRadius = {
  ...defaultTheme.borderRadius,
  'hero-flare': '632px',
  hero: '1200px',
};

module.exports = config;
